version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "
        while ! nc -z db 3306;
        do
          echo 'Waiting for MySQL to be ready...';
          sleep 2;
        done;
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8001:8000"  # Cambiado de 8000 a 8001
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=seguimiento_db
      - DJANGO_DB_USER=seguimiento_user
      - DJANGO_DB_PASSWORD=seguimiento_password

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=seguimiento_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=seguimiento_user
      - MYSQL_PASSWORD=seguimiento_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3307:3306"  # Cambiado de 3307:3307 a 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:81"  # Cambiado de 8081 a 8082
    environment:
      - PMA_HOST=db
      - PMA_USER=seguimiento_user
      - PMA_PASSWORD=seguimiento_password
    depends_on:
      - db

volumes:
  mysql_data:
