# Generated by Django 5.0.6 on 2025-04-08 03:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Docente'), ('department_head', 'Jefe de Departamento')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(max_length=10)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('docencia', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tutoria', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gestion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('resultado_global', models.DecimalField(decimal_places=2, max_digits=3)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.docente')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('formacion_docente', models.IntegerField()),
                ('planeacion_evaluacion', models.IntegerField()),
                ('estrategias_didacticas', models.IntegerField()),
                ('asesoria_estudiantes', models.IntegerField()),
                ('participacion_tutor', models.IntegerField()),
                ('gestion_tutorial', models.IntegerField()),
                ('resultado_final', models.DecimalField(decimal_places=2, max_digits=3)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('grupo', models.CharField(max_length=10)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.docente')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('dominio_asignatura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('planificacion_curso', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ambientes_aprendizaje', models.DecimalField(decimal_places=2, max_digits=3)),
                ('estrategias_tecnicas', models.DecimalField(decimal_places=2, max_digits=3)),
                ('motivacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('evaluacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comunicacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gestion_curso', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tecnologias_informacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('satisfaccion_general', models.DecimalField(decimal_places=2, max_digits=3)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.materia')),
            ],
        ),
    ]
