# Generated by Django 5.0.6 on 2025-03-27 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_general', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.docente')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.semestre')),
            ],
        ),
    ]
