# Generated by Django 5.0.6 on 2025-03-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='carrera',
            field=models.CharField(choices=[('INF', 'Ingeniería en Informática'), ('ISC', 'Ingeniería en Sistemas Computacionales')], default='INF', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docente',
            name='apellidos',
            field=models.CharField(max_length=200),
        ),
    ]
