# Generated by Django 5.0.6 on 2025-04-08 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionalumno',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.estudiante'),
        ),
        migrations.AlterField(
            model_name='evaluacionalumno',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
