# Generated by Django 5.2 on 2025-04-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_evaluacionalumno_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='rfc',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
